language: generic
install:
  - curl -O -J -L https://github.com/nxadm/rakudo-pkg/releases/download/v2026.04/rakudo-pkg-Ubuntu26.04_2026.04-01_amd64.deb
  - sudo dpkg -i rakudo-pkg-Ubuntu26.04_2026.04-01_amd64.deb
  - export PATH=/opt/rakudo/bin:~/.raku/bin:$PATH
  - git clone https://github.com/ugexe/zef $HOME/zef
  - raku -I $HOME/zef/lib $HOME/zef/bin/zef --depsonly install .
  - raku -I $HOME/zef/lib $HOME/zef/bin/zef --force --/test install .
script:
  - zef test -v ./
